version: "3"
services:
  web:
    image: tamborello/get-started:lisp-app
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
# Do I need this statement if I'm not remapping ports?
# Yes, that's how I tell Docker to publish a port from the node.
    ports:
     - "8000:8000"
    networks:
     - webnet
networks:
 webnet: